### ISSUE TITLE
Add "<sec:logout/>"

### ISSUE THREAD

**Issue by btsatoutkzy** [terasolunaorg/terasoluna-gfw-web-blank#164]
## Description
Add "<sec:logout/>" to spring-security.xml.

## Possible Solutions
 * Add "<sec:logout/>" to spring-security.xm

## Fix Version/s
- [ ] 5.1.0

## Issue Links
N/A

**Comment by kazuki43zoo** [comment]
@btsatoukzn 

Please resolve with #159 .
