### ISSUE TITLE
Occur the warning of selenium version in pom.xml

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw-web-blank#297]
## Description
Occur the warning that indicate overriding dependency version of selenium managed by super pom at Eclipse POM Editor.

## Possible Solutions

Change to manage version using `<dependencyManagement>` like [terasoluna-gfw-web-multi-blank](https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/blob/3b843a2232e1337ca43b7e59fe4233de104e5144/pom.xml#L132-L171).

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)

## Final Solution
(To be written later by project member)

## Migrating Guide
(To be selected later by project member)
* [ ] Required
* Not Required

## Issue Links
* #XXX

**Comment by itouyun** [comment]
Is this lack of consideration for horizontal expansion from `terasoluna-gfw-web-multi-blank`?

**Comment by kazuki43zoo** [comment]
> Is this lack of consideration for horizontal expansion from terasoluna-gfw-web-multi-blank?

Probably, yes.
I think #246 is incorrect fixes.

**Comment by kazuki43zoo** [comment]
This issue should be consider together with terasolunaorg/terasoluna-gfw-web-multi-blank#333 .

Thanks.

**Comment by itouyun** [comment]
@kazuki43zoo 
Thank you. 
We will consider solution by terasolunaorg/terasoluna-gfw-web-multi-blank#333 and this issue.

**Comment by btyanagawamg** [comment]
@kazuki43zoo @itouyun @yoshikawaa 
We will deal with this issue in #315 .(We will take the same action as the correspondence of terasolunaorg/terasoluna-gfw-web-multi-blank#333 )
So I will close this issue .
Thank you .
