### ISSUE TITLE
unhandledSystemError.html is not displayed when Internet Explorer is a support browser.

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/terasoluna-gfw-web-blank#324]
## Description
unhandledSystemError.html is not displayed when Internet Explorer is a support browser.
Because [when Internet Explorer is a support browser, implementation should be such that size of the HTML responded as error screen should be 513 bytes or more](http://terasolunaorg.github.io/guideline/5.3.1.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.html#exception-handling-how-to-use-codingpoint-jsp-label), but now unhandledSystemError.html does not.

## Possible Solutions
add `<br>` tag properly.

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.x
- [x] 5.3.x
- [x] 5.2.x
- [x] 5.1.x
- [x] 5.0.x
- [x] 1.0.x

## Final Solution
(To be written later by project member)

## Migrating Guide
(To be selected later by project member)
* [ ] Required
* Not Required

## Issue Links
* #XXX

**Comment by yoshikawaa** [comment]
@btyanagawamg 
Please create issue for migration guide.
And check guideline whether require to reflect this change or not.

**Comment by btyanagawamg** [comment]
I made ISSUE for migration guide and disscussed and decided whether it is needed.
As a result, it was judged that this ISSUE modification is not necessary as a migration procedure.
For this reason, I will close this ISSUE.
