### ISSUE TITLE
encoding property is missing in pom.xml.

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/terasoluna-gfw-web-blank#364]
## Description
`encoding` property is missing.

* single blank
https://github.com/terasolunaorg/terasoluna-gfw-web-blank/blob/df8bcaf7429aff5f3757a0df5998b85b4d22d6bf/pom.xml#L268-L269

* multi module blank
https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/blob/7a24a2d1ceb5435601dd246d6983f1196e911274/pom.xml#L179-L181

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
 - [x] master
 - [x] 5.4.x
 - [x] 1.6.x(m_t)
 - [x] 1.5.x(m_t)
 - [x] 1.6.x(m_j)
 - [x] 1.5.x(m_j)

## Final Solution
(To be written later by project member)

## Migrating Guide
(To be selected later by project member)
* [ ] Required
* Not Required

## Issue Links
* #XXX

**Comment by hirakuriy** [comment]
@btiwahorisu 
Thank you for fixing this.
Please write fix versions, and backport if necessary.
