### ISSUE TITLE
[Selenium 3.0] Update from Selenium 2 to 3

### ISSUE THREAD

**Issue by btiwahorisu** [terasolunaorg/terasoluna-gfw-web-blank#382]
## Description
Update selenium ver 2 to 3.

## Possible Solutions
- Update Selenium version to `3.0.1`

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.5.x(master)
- [x] 1.6.0(m-j)
- [x] 1.6.0(m-t)

## Final Solution
(To be written later by project member)

## Migrating Guide
(To be selected later by project member)
* [ ] Required
* Not Required

## Issue Links
* #XXX

**Comment by yoshikawaa** [comment]
@btiwahorisu @hirakuriy 
Why add selenium dependencies to blank project pom...
It is only the requirement of our functional test that we want to use Selenium 3.0.1, it is a problem not related to users who use blank project. We should not force to use Selenium 3.0.1.
**In previous( #315 ), We removed them and use Spring IO Platform default version at blank project.**
