### ISSUE TITLE
Need to override <developers> and <scm> on pom.xml

### ISSUE THREAD

**Issue by btiwahorisu** [terasolunaorg/terasoluna-gfw-web-blank#415]
## Description
Since tags `<developers>`, `<scm>` are set in terasoluna-gfw, when using an empty project, the values are used by default.
https://github.com/terasolunaorg/terasoluna-gfw/blob/035941b7251dc93c3112ab2342589dd60b501744/pom.xml#L23-L34

The tags `<developers>`, `<scm>` are not set to an empty project, so users will have to add the tags themselves when modifying the tags.

Therefore, the corresponding tag is set in advance for the blank project.
## Possible Solutions
Add tag `<developers>`, `<scm>` to pom.xml.

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [ ] 5.6.0 (master)
- [ ] 5.5.2 (5.5.x)
- [ ] 5.4.2 (5.4.x)
- [ ] 1.7.0 (m-j/master)
- [ ] 1.6.2 (m-j/1.6.x)
- [ ] 1.5.2 (m-j/1.5.x)
- [ ] 1.7.0 (m-t/master)
- [ ] 1.6.2 (m-t/1.6.x)
- [ ] 1.5.2 (m-t/1.5.x)

## Issue Links
- xxx

**Comment by yoshikawaa** [comment]
We won't fix at #416 .
