### ISSUE TITLE
Blank eclipse project (WTP) puts runtime scoped libraries in wrong directory.

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/terasoluna-gfw-web-blank#437]
## Description

https://github.com/terasolunaorg/terasoluna-gfw-web-blank/blob/a70e632e3d22ecf39cf6376b281227ba87016271/unmaven-project.sh#L26-L37

`WEB-INF/lib`, `libsrc` directory must contain compile and runtime scoped jars, but does not actually include runtime scoped jars.
Conversely, the `testlib` directory should not contain compile and runtime scoped jars, but actually contains runtime scoped jars.

> Note:
> This issue is not affect multi-module projects, because it is not provide the Blank eclipse project (WTP).

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

## Affect versions
> Version in which the problem occurs. **Current version if not known.**
> If there is a feature suggestion, please delete it.

- 5.5.1.RELEASE and earlier all versions.

## Fix repositories
> Repositories to fix with this issue.

- [x] terasoluna-gfw-web-blank

## Issue links
> Links to related issues.

- #xx

**Comment by yoshikawaa** [comment]
Please close after considering whether to need or not backport.

**Comment by takahashihrzg** [comment]
The scope of the backport will be determined in future discussions.

**Comment by yoshikawaa** [comment]
> The scope of the backport will be determined in future discussions.

In terms of quality, it's better to backport to all maintenance versions since 1.0.x due to a fatal non-bootable bug.
In terms of release, it is unknown which version is subject to normal maintenance, emergency maintenance, or EOL, and it is necessary to consider it.
