### ISSUE TITLE
Replace @RequestMapping with @GetMapping or @PostMapping

### ISSUE THREAD

**Issue by btonokit** [terasolunaorg/terasoluna-gfw-web-blank#502]
## Description
> Please write the problem in detail.
> Please write based on facts as much as possible, and post links to references/Javadoc or stack traces.

Replace `@RequestMapping` with `@GetMapping` or `@PostMapping`, which is highly readable and does not accept extra request methods.

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

In the blank project, `@RequestMapping` is used as the controller to the top page. There, both Get and Post methods are used for mapping, but since Get alone seems to be sufficient, `@GetMapping` is used.

## Affect versions
> Version in which the problem occurs. **Current version if not known.**
> If there is a feature suggestion, please delete it.

- 5.7.0.RELEASE

## Fix repositories
> Repositories to fix with this issue.

- [x] terasoluna-gfw-web-blank
- [x] m-j
- [x] m-t

## Issue links
> Links to related issues.

- #xx

**Comment by btiwahorisu** [comment]
Closing this as I made the following changes:
https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/542
