### ISSUE TITLE
Reflect: Change BeanMapper from Dozer to MapStruct

### ISSUE THREAD

**Issue by btonokit** [terasolunaorg/terasoluna-gfw-web-blank#525]
## Original Issue
> Links to the original issues.

- Reflect https://github.com/terasolunaorg/terasoluna-gfw/issues/1183

## Description
> Please write if the description of the original issue is not enough.
> Please write based on facts as much as possible, and post links to references/Javadoc or stack traces.

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

- Remove Dozer configuration from `applicationContext.xml`
- Remove `dozer.poperties`
- Add `.factorypath` to `.gitignore`
  - `.factorypath` is a file generated by eclipse and used for annotation processing.
In other words, it does not need to be managed by Git.

## Fix repositories
> Repositories to fix with this issue.

- [x] terasoluna-gfw-web-blank
- [x] m-j
- [x] m-t

## Issue links
> Links to related issues.

- #xx

**Comment by yoshikawaa** [comment]
https://mapstruct.org/faq/#Can-I-use-MapStruct-together-with-Project-Lombok

You can provide setting mock for using MapStruct+Lombok.

https://mapstruct.org/documentation/stable/reference/html/#configuration-options

You can provide `mapstruct.defaultComponentModel=spring` for auto wiring. (Blank or Parent)

**Comment by btonokit** [comment]
> You can provide setting mock for using MapStruct+Lombok.
> You can provide mapstruct.defaultComponentModel=spring for auto wiring. (Blank or Parent)

After discussion, it was decided to set both to gfw-parent.

**Comment by btonokit** [comment]
Since it is completely up to the user whether to use Lombok or MapStruct, we concluded that it would be better to allow the user to choose in a blank project.

https://github.com/terasolunaorg/terasoluna-gfw/pull/1184#discussion_r969464768
https://github.com/terasolunaorg/terasoluna-gfw/pull/1184#discussion_r970447422
